### ISSUE TITLE
missing parenthesis in output_parsers.js used in Web UI demo.

### ISSUE THREAD

**Issue by scotth1** [deepmind/dramatron#11]
In the linked Web UI demo page at https://deepmind.github.io/dramatron/

Uncaught SyntaxError: Unexpected token '{' (at VM52 output_parsers.js:108:38)
```
export function extractPlaceNames(scenes) {
  if (scenes.includes(prefixes.END_MARKER)) {
    scenes = scenes.split(prefixes.END_MARKER)[0];
  }
  const places = [];
  for (const place of scenes.matchAll(PLACE_REGEX)) {
    if (place.length >= 3) {
108>>      if (!places.includes(place[2]) {
        places.push(place[2]);
      }
    }
  }
  return places;
```

**Comment by korymath** [comment]
Thank you for flagging this. 
Fixed with: https://github.com/deepmind/dramatron/commit/57875b83b8128f681e095c795481b8de5f8ad143
Should redeploy shortly.
